/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package astrologiacalciatori;

import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import javax.swing.SwingUtilities;

/**
 *
 * @author zxt02
 */
public class Form extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form.class.getName());
    
    private Gestore g = new Gestore("sportivi.csv", "zodiaco.csv");
    private ArrayList<Zodiaco> zodiaco =  new ArrayList<>();
    private int[] scala =  new int[12];
    private ArrayList<JLabel> zodiacoLabel =  new ArrayList<>();
    private ArrayList<JLabel> scalaLabel =  new ArrayList<>();
    private ArrayList<JProgressBar> progressBar =  new ArrayList<>();
    private int max;
    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
        
        zodiacoLabel.add(lbl1);
        zodiacoLabel.add(lbl2);
        zodiacoLabel.add(lbl3);
        zodiacoLabel.add(lbl4);
        zodiacoLabel.add(lbl5);
        zodiacoLabel.add(lbl6);
        zodiacoLabel.add(lbl7);
        zodiacoLabel.add(lbl8);
        zodiacoLabel.add(lbl9);
        zodiacoLabel.add(lbl10);
        zodiacoLabel.add(lbl11);
        zodiacoLabel.add(lbl12);
        
        scalaLabel.add(lblGoal1);
        scalaLabel.add(lblGoal2);
        scalaLabel.add(lblGoal3);
        scalaLabel.add(lblGoal4);
        scalaLabel.add(lblGoal5);
        scalaLabel.add(lblGoal6);
        scalaLabel.add(lblGoal7);
        scalaLabel.add(lblGoal8);
        scalaLabel.add(lblGoal9);
        scalaLabel.add(lblGoal10);
        scalaLabel.add(lblGoal11);
        scalaLabel.add(lblGoal12);
        
        progressBar.add(jProgressBar1);
        progressBar.add(jProgressBar2);
        progressBar.add(jProgressBar3);
        progressBar.add(jProgressBar4);
        progressBar.add(jProgressBar5);
        progressBar.add(jProgressBar6);
        progressBar.add(jProgressBar7);
        progressBar.add(jProgressBar8);
        progressBar.add(jProgressBar9);
        progressBar.add(jProgressBar10);
        progressBar.add(jProgressBar11);
        progressBar.add(jProgressBar12);
        
    }
    
    /**
     * Aggiorna il progress bar
     * 
     * @param p la barra da aggiornare
     * @param g il numero tatole di goal da raggiungere
     */
    public void setProgressBar(JProgressBar p, int g){
        new Thread(() -> {
            p.setMaximum(max);
        for(int i = 0; i <= g; i++){
            final int value = i;

            SwingUtilities.invokeLater(() -> {
                p.setValue(value);
            });

            try {
                Thread.sleep(1);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }).start();
    }
    
    /**
     * Aggiorna le euchette e imposta i progress bar
     */
    public void setLabels(){
        for(int i = 0; i < zodiaco.size(); i++){
            zodiacoLabel.get(i).setText(zodiaco.get(zodiaco.size() - i - 1).getNome());
        }
        for(int i = 0; i < scala.length; i++){
            scalaLabel.get(i).setText("" + scala[scala.length - i - 1]);
            setProgressBar(progressBar.get(i), scala[scala.length - i - 1]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        lbl2 = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();
        lbl3 = new javax.swing.JLabel();
        jProgressBar3 = new javax.swing.JProgressBar();
        lbl4 = new javax.swing.JLabel();
        jProgressBar4 = new javax.swing.JProgressBar();
        lbl5 = new javax.swing.JLabel();
        jProgressBar5 = new javax.swing.JProgressBar();
        lbl6 = new javax.swing.JLabel();
        jProgressBar6 = new javax.swing.JProgressBar();
        lbl7 = new javax.swing.JLabel();
        jProgressBar7 = new javax.swing.JProgressBar();
        lbl8 = new javax.swing.JLabel();
        jProgressBar8 = new javax.swing.JProgressBar();
        lbl9 = new javax.swing.JLabel();
        jProgressBar9 = new javax.swing.JProgressBar();
        lbl10 = new javax.swing.JLabel();
        jProgressBar10 = new javax.swing.JProgressBar();
        lbl11 = new javax.swing.JLabel();
        jProgressBar11 = new javax.swing.JProgressBar();
        lbl12 = new javax.swing.JLabel();
        jProgressBar12 = new javax.swing.JProgressBar();
        lblGoal1 = new javax.swing.JLabel();
        lblGoal2 = new javax.swing.JLabel();
        lblGoal3 = new javax.swing.JLabel();
        lblGoal4 = new javax.swing.JLabel();
        lblGoal5 = new javax.swing.JLabel();
        lblGoal6 = new javax.swing.JLabel();
        lblGoal7 = new javax.swing.JLabel();
        lblGoal8 = new javax.swing.JLabel();
        lblGoal9 = new javax.swing.JLabel();
        lblGoal10 = new javax.swing.JLabel();
        lblGoal11 = new javax.swing.JLabel();
        lblGoal12 = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(221, 238, 255));

        lblTitle.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(102, 102, 255));
        lblTitle.setText("Istogramma");

        lbl1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl1.setForeground(new java.awt.Color(0, 0, 153));
        lbl1.setText("n1");

        jProgressBar1.setBackground(new java.awt.Color(176, 238, 255));
        jProgressBar1.setMaximum(50);

        lbl2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl2.setForeground(new java.awt.Color(0, 0, 153));
        lbl2.setText("n2");

        jProgressBar2.setBackground(new java.awt.Color(204, 204, 255));
        jProgressBar2.setMaximum(50);

        lbl3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl3.setForeground(new java.awt.Color(0, 0, 153));
        lbl3.setText("n3");

        jProgressBar3.setBackground(new java.awt.Color(255, 204, 255));
        jProgressBar3.setMaximum(50);

        lbl4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl4.setForeground(new java.awt.Color(0, 0, 153));
        lbl4.setText("n4");

        jProgressBar4.setBackground(new java.awt.Color(255, 204, 204));
        jProgressBar4.setMaximum(50);

        lbl5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl5.setForeground(new java.awt.Color(0, 0, 153));
        lbl5.setText("n5");

        jProgressBar5.setBackground(new java.awt.Color(255, 255, 204));
        jProgressBar5.setMaximum(50);

        lbl6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl6.setForeground(new java.awt.Color(0, 0, 153));
        lbl6.setText("n6");

        jProgressBar6.setBackground(new java.awt.Color(204, 255, 204));
        jProgressBar6.setMaximum(50);

        lbl7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl7.setForeground(new java.awt.Color(0, 0, 153));
        lbl7.setText("n7");

        jProgressBar7.setBackground(new java.awt.Color(102, 255, 255));
        jProgressBar7.setMaximum(50);

        lbl8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl8.setForeground(new java.awt.Color(0, 0, 153));
        lbl8.setText("n8");

        jProgressBar8.setBackground(new java.awt.Color(102, 204, 255));
        jProgressBar8.setMaximum(50);

        lbl9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl9.setForeground(new java.awt.Color(0, 0, 153));
        lbl9.setText("n9");

        jProgressBar9.setBackground(new java.awt.Color(255, 153, 255));
        jProgressBar9.setMaximum(50);

        lbl10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl10.setForeground(new java.awt.Color(0, 0, 153));
        lbl10.setText("n10");

        jProgressBar10.setBackground(new java.awt.Color(255, 204, 153));
        jProgressBar10.setMaximum(50);

        lbl11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl11.setForeground(new java.awt.Color(0, 0, 153));
        lbl11.setText("n11");

        jProgressBar11.setBackground(new java.awt.Color(255, 255, 153));
        jProgressBar11.setMaximum(50);

        lbl12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl12.setForeground(new java.awt.Color(0, 0, 153));
        lbl12.setText("n12");

        jProgressBar12.setBackground(new java.awt.Color(153, 255, 204));
        jProgressBar12.setMaximum(50);

        lblGoal1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGoal1.setForeground(new java.awt.Color(0, 153, 153));

        lblGoal2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGoal2.setForeground(new java.awt.Color(0, 153, 153));

        lblGoal3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGoal3.setForeground(new java.awt.Color(0, 153, 153));

        lblGoal4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGoal4.setForeground(new java.awt.Color(0, 153, 153));

        lblGoal5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGoal5.setForeground(new java.awt.Color(0, 153, 153));

        lblGoal6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGoal6.setForeground(new java.awt.Color(0, 153, 153));

        lblGoal7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGoal7.setForeground(new java.awt.Color(0, 153, 153));

        lblGoal8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGoal8.setForeground(new java.awt.Color(0, 153, 153));

        lblGoal9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGoal9.setForeground(new java.awt.Color(0, 153, 153));

        lblGoal10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGoal10.setForeground(new java.awt.Color(0, 153, 153));

        lblGoal11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGoal11.setForeground(new java.awt.Color(0, 153, 153));

        lblGoal12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGoal12.setForeground(new java.awt.Color(0, 153, 153));

        btnStart.setBackground(new java.awt.Color(0, 204, 204));
        btnStart.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnStart.setForeground(new java.awt.Color(255, 255, 255));
        btnStart.setText("Start");
        btnStart.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnStart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setText("i goal attribuibili a ciascun segno zodiaco");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(215, 215, 215))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(183, 183, 183))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressBar12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jProgressBar11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jProgressBar10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jProgressBar9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jProgressBar8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jProgressBar7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jProgressBar6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jProgressBar5, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jProgressBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGoal1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGoal2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGoal3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGoal4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGoal5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGoal6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGoal7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGoal8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGoal9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGoal10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGoal11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGoal12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblGoal1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblGoal2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblGoal3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jProgressBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblGoal4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jProgressBar5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblGoal5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jProgressBar6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblGoal6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jProgressBar7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblGoal7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jProgressBar8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblGoal8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jProgressBar9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblGoal9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jProgressBar10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblGoal10))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jProgressBar11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblGoal11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jProgressBar12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblGoal12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        btnStart.setEnabled(false);
        try {
            g.readFiles();
        } catch (IOException ex) {
            System.getLogger(Form.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        g.setZodiaco();
        g.calcolaGoal();
        g.ordinaZodiaco();
        zodiaco = g.getZodiaco();
        scala = g.getScala();
        g.setMax();
        max = g.getMax();
        setLabels();
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Form().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar10;
    private javax.swing.JProgressBar jProgressBar11;
    private javax.swing.JProgressBar jProgressBar12;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar4;
    private javax.swing.JProgressBar jProgressBar5;
    private javax.swing.JProgressBar jProgressBar6;
    private javax.swing.JProgressBar jProgressBar7;
    private javax.swing.JProgressBar jProgressBar8;
    private javax.swing.JProgressBar jProgressBar9;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl12;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JLabel lblGoal1;
    private javax.swing.JLabel lblGoal10;
    private javax.swing.JLabel lblGoal11;
    private javax.swing.JLabel lblGoal12;
    private javax.swing.JLabel lblGoal2;
    private javax.swing.JLabel lblGoal3;
    private javax.swing.JLabel lblGoal4;
    private javax.swing.JLabel lblGoal5;
    private javax.swing.JLabel lblGoal6;
    private javax.swing.JLabel lblGoal7;
    private javax.swing.JLabel lblGoal8;
    private javax.swing.JLabel lblGoal9;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
